### ISSUE TITLE
Fresh animation/ The wolf is stuck in sitting animation

### ISSUE THREAD

**Issue by Hikisan123** [MehVahdJukaar/Christmas#60]
https://github.com/MehVahdJukaar/SnowySpirit/assets/122529044/efe4a8df-cf35-4c4f-9a1a-d709e266762f

**Comment by Aabaddon** [comment]
i...i almost died laughing, it looks like my dog on the carpet, sorry this has nothing to do but it was hilarious

**Comment by MehVahdJukaar** [comment]
the mod uses mixins to have a rider (wolf) not be in sitting pose. I used some sutff that made it compatible with optifine but apaternly more direct compatibility is needed here

**Comment by MehVahdJukaar** [comment]
also name of the mod is EMF

**Comment by peow** [comment]
is this problem unfixable?

**Comment by peow** [comment]
i can imagine a possible fix being a texture pack that changes the wolf's texture only when he is tied to a sled, so when placing this texture above FreshAnimations, it will overlap the wolf's texture from FreshAnimations and thus it will no longer be buggy

**Comment by peow** [comment]
i don't understand what its like to make mod so i could be very wrong

looking at the information about the entity "sled", when a wolf is tied to it says this:

/summon snowyspirit:sled [...much data], id: "minecraft:wolf", UUID: [I; 21794706, 1671839899, -1969550769, 1393188351], Age: 0, CollarColor: 14b]

Since it is possible to know which wolf is tied, you could perhaps add a configuration that changes the wolf's name to for example, "Snow Wolf", and saves the previous name as a variable like %oldname, so the Texture Pack will recognize this wolf and It will change his skin to the standard Minecraft wolf (i've seen many textures configurated to only recognize a renamed item, like a sword named "Angel Sword"), and when taking the wolf out of the sled, his original name would return and so the Texture Pack would no longer affect it

**Comment by MehVahdJukaar** [comment]
> why not simply rename the wolf? It wouldn't make sense for sleds to magically change a wolf name

**Comment by peow** [comment]
you didnt understand, the purpose of the mod to change the wolf's name is so that the custom texture I suggested would recognize this wolf and thus change his skin to the default one, no longer having the FreshAnimations animations, thus no longer causing bugs in the sled

**Comment by MehVahdJukaar** [comment]
ah. sort of hack. I have a better solution tho. the wolf sitting thing require d avery accurate mixin that also needed to account for optifine. I could discard that part (since theres no reason anybody should ever usa that mess of a mod) and focus on something that would be compaitble with that mod. It will probably involved having mixins into that other mod mixins, very cursed but they seem to alter things quite a bit so tahts the only option. if it was easier i would hav edone sooner but it requires some mod surgery

**Comment by peow** [comment]
hmmm okay, is that its disappointing to have to use the sled with the wolf sitting if you want to continue with FreshAnimations

**Comment by MehVahdJukaar** [comment]
added in 1.20
